.TH "ARCH-UPDATE" "1" "Novembre 2024" "Arch-Update 3.4.1" "Manuel de Arch-Update"

.SH NAME
arch-update \- Un notificateur & applicateur de mises à jour pour Arch Linux qui vous assiste dans les tâches importantes d'avant / après mise à jour.

.SH SYNOPSIS
.B arch-update
[\fI\,OPTION\/\fR]

.SH DESCRIPTION
Un notificateur & applicateur de mises à jour pour Arch Linux qui vous assiste dans les tâches importantes d'avant / après mise à jour et qui inclut une applet systray cliquable pour une intégration facile avec n'importe quel panneau sur n'importe quel environnement de bureau ou gestionnaire de fenêtres.
.br
.RB "Prise en charge optionnelle des mises à jour des paquets AUR (via " "paru" ", " "yay " "ou " "pikaur" "), des mises à jour des paquets Flatpak (via " "flatpak" ") et des notifications de bureau (via " "libnotify" ")."
.br
Arch-Update est conçu pour suivre les étapes usuelles de maintenance du système, telles que décrites dans le Arch Wiki à https://wiki.archlinux.org/title/System_maintenance.

.SH OPTIONS
.PP
Si aucune option n'est passée, lance la série de fonctions adéquates pour effectuer une mise à jour complète et correcte, en commençant par afficher la liste des paquets disponibles pour la mise à jour et en demandant la confirmation de l'utilisateur pour procéder à l'installation.
.br
.RB "Supporte les mises à jour des paquets AUR (si " "paru" ", " "yay " "ou " "pikaur " "est installé) et des paquets Flatpak (si " "flatpak " "est installé)."
.br
Avant d'effectuer la mise à jour, propose d'afficher les dernières Arch news à l'utilisateur. Par défaut, les Arch news sont seulement affichées si au moins une nouvelle news a été publiée depuis la dernière exécution. Les Arch news publiées depuis la dernière exécution ou à la même date sont étiquetées comme '[NOUVEAU]'.
.br
Arch-Update vérifie aussi la présence de paquets orphelins & inutilisés, d'anciens paquets mis en cache, de fichiers pacnew & pacsave, les mises à jour du noyau en attente ainsi que les services nécessitant un redémarrage après mise à jour et, s'il y en a, propose de les traiter.
.br
Ces fonctions sont lancées quand vous cliquez sur l'applet systray.

.PP

.TP
.B \-c, \-\-check
Vérifier les mises à jour disponibles.
.br
Change l'icône du systray et envoie une notification de bureau contenant le nombre de mises à jour disponibles (s'il y a des nouvelles mises à jour disponibles depuis le dernier check).
.br
.RB "Supporte les mises à jour des paquets AUR (si " "paru" ", " "yay " "ou " "pikaur " "est installé) et les mises à jour des paquets Flatpak (si " "flatpak " "est installé)."
.br
.RB "L'option " "\-\-check " "est automatiquement lancée au démarrage du système puis une fois chaque heure si vous avez activé le " "systemd.timer " "associé avec la commande suivante :"
.br
.B systemctl \-\-user enable \-\-now arch-update.timer

.TP
.B \-l, \-\-list
Afficher la liste des mises à jour en attente.

.TP
.B \-d, \-\-devel
Inclure les mises à jour des paquets de développement AUR.

.TP
.B \-n, \-\-news
Afficher les dernières Arch news.
.br
.RB "Vous pouvez optionnellement spécifier combien de Arch news afficher en tant qu'argument, comme ceci : " "arch-update --news 10" ". La valeur par défaut est 5."

.TP
.B \-D, \-\-debug
Afficher les traces de débogage.

.TP
.B \-\-gen\-config
.RB "Générer un fichier de configuration " "arch-update.conf " "par défaut / exemple (voir la page de manuel " "arch-update.conf(5) " "pour plus de détails)."
.br
.RB "Vous pouvez optionnellement passer l'argument " "--force " "pour écraser un fichier de configuration " "arch-update.conf " "existant."

.TP
.B \-\-show\-config
.RB "Afficher le fichier de configuration " "arch-update.conf " "actuellement utilisé (s'il existe)."

.TP
.B \-\-edit\-config
.RB "Editer le fichier de configuration " "arch-update.conf " "actuellement utilisé (s'il existe)."

.TP
.B \-\-tray
Démarrer l'applet systray d'Arch-Update.
.br
.RB "Pour la démarrer automatiquement au démarrage du système, vous pouvez soit exécuter la commande " "arch-update --tray --enable " "(méthode recommandée pour la plupart des environnements de bureau, utilise XDG Autostart) ou vous pouvez activer le service systemd associé (dans le cas où vôtre environnement de bureau ne supporte pas XDG Autostart) en exécutant " "systemctl \-\-user enable \-\-now arch-update-tray.service".
.br
.RB "Si vous utilisez un gestionnaire de fenêtres ou un compositeur Wayland, vous pouvez plutôt ajouter la commande " "arch-update --tray " "à vos applications auto-start dans votre fichier de configuration."

.TP
.B \-v, \-\-version
Afficher les informations de version.

.TP
.B \-h, \-\-help
Afficher le message d'aide.

.TP
.RB "Certaines options peuvent être activées, désactivées ou modifiées via le fichier de configuration " "arch-update.conf " ", voir la page de manuel " "arch-update.conf(5)".

.SH UTILISATION
.TP
.B L'applet systray
.RB "Pour démarrer l'applet systray, lancez l'application " "Arch-Update Systray Applet " "depuis votre menu d'application."

Pour la démarrer automatiquement au démarrage du système, utilisez l'une des options suivantes :

.RB "- Lancer la commande suivante (méthode recommandée pour la plupart des environnements de bureau, utilise XDG Autostart) : " "arch-update \-\-tray \-\-enable"
.br
.RB "- Activer le service systemd associé (dans le cas où votre environnement de bureau ne supporte pas XDG Autostart) : " "systemctl \-\-user enable \-\-now arch-update-tray.service"

.RB "Si vous utilisez un gestionnaire de fenêtre ou un compositeur Wayland, vous pouvez plutôt ajouter la commande " "arch-update \-\-tray " "à vos applications auto-start dans votre fichier de configuration."

.BR "Si l'applet systray ne démarre pas au démarrage du système malgré tout" ", veuillez lire le chapitre " "'l'applet systray ne démarre pas au démarrage du système' " "dans la section " "Trucs et Astuces " "ci-dessous."

.RB "L'icône du systray changera automatiquement en fonction de l'état actuel de votre système ('à jour' ou 'mises à jour disponibles'). Lorsque vous cliquez dessus, elle lance " "arch-update " "via le fichier " "arch-update.desktop".

.RB "L'applet systray essaie de lire le fichier " "arch-update.desktop " "dans les chemins ci-dessous avec l'ordre suivant :"

\- $XDG_DATA_HOME/applications/arch-update.desktop
.br
\- $HOME/.local/share/applications/arch-update.desktop
.br
\- $XDG_DATA_DIRS/applications/arch-update.desktop
.br
\- /usr/local/share/applications/arch-update.desktop <-- Chemin d'installation par défaut lorsque vous installez Arch-Update depuis la source
.br
\- /usr/share/applications/arch-update.desktop <-- Chemin d'installation par défaut lorsque vous installez Arch-Update depuis le AUR

.RB "Dans le cas où vous avez envie (ou besoin) de personnaliser le fichier " "arch-update.desktop" ", copiez le dans un chemin qui a une priorité plus élevée que le chemin d'installation par défaut et modifier le ici (afin d'assurer que votre ficher " "arch-update.desktop " "personnalisé remplace celui par défaut et que vos modifications ne soient pas écrasées à chaque mise à jour)."

.br
.RB "Cela peut être utile pour forcer le fichier " "arch-update.desktop " "à lancer " "Arch-Update " "dans un émulateur de terminal spécifique par exemple."
.br
.BR "Si cliquer sur l'applet systray ne fait rien" ", veuillez lire le chapitre " "'Forcer le fichier desktop à se lancer avec un émulateur de terminal spécifique' " "dans la section " "Trucs et Astuces " "ci-dessous."

.TP
.B Le timer systemd
.RB "Il existe un service systemd dans " "/usr/lib/systemd/user/arch-update.service " "(ou dans " "/etc/systemd/user/arch-update.service " "si vous avez installé arch-update depuis la source) qui exécute la fonction " "\-\-check " "quand il est démarré. Pour le démarrer automatiquement " "au démarrage du système puis une fois toutes les heures, " "activez le timer systemd associé (vous pouvez modifier le cycle de vérification automatique à votre guise, voir le chapitre TRUCS ET ASTUCES ci-dessous) :"
.br
.B systemctl \-\-user enable \-\-now arch-update.timer

.SH TRUCS ET ASTUCES
.TP
.B Prise en charge du AUR
.RB "Arch-Update prend en charge la mise à jour des paquets AUR lors de la vérification et de l'installation des mises à jour si " "paru" ", " "yay " "ou " "pikaur " "est installé."
.br
Voir https://github.com/morganamilo/paru et https://aur.archlinux.org/packages/paru
.br
Voir https://github.com/Jguer/yay et https://aur.archlinux.org/packages/yay
.br
Voir https://github.com/actionless/pikaur et https://aur.archlinux.org/packages/pikaur

.TP
.B Prise en charge de Flatpak
.RB "Arch-Update prend en charge la mise à jour des paquets Flatpak lors de la vérification et de l'installation des mises à jour (ainsi que de la suppression des paquets Flatpak inutilisés) si " "flatpak " "est installé."
.br
Voir https://www.flatpak.org/ et https://archlinux.org/packages/extra/x86_64/flatpak/

.TP
.B Notifications de bureau
.RB "Arch-Update prend en charge les notifications de bureau lors de l'exécution de la fonction " "--check " "si " "libnotify (notify-send) " "est installé."
.br
Voir https://wiki.archlinux.org/title/Desktop_notifications

.TP
.B L'applet systray ne démarre pas au démarrage du système

.RB "Assurez vous d'avoir suivi les instructions du chapitre " "l'applet systray " "dans la section " "Utilisation " "ci-dessus."

.RB "Si l'applet systray ne démarre pas malgré tout, cela peut être le résultat d'une " "situation de compétition".
.RB "Dans ce cas, il peut être utile de légèrement retarder le démarrage de l'applet systray en utilisant une déclaration " "sleep " "au préalable :"

.RB "\- Si vous avez utilisé " "arch-update --tray --enable" ", modifiez la ligne " "Exec= " "dans le fichier " "arch-update-tray.desktop " "(qui se trouve sous " "~/.config/autostart/ " "par défaut), comme ceci :"
.br
Exec=sh -c "sleep 3 && arch-update --tray"

.RB "\- Si vous avez utilisé le service systemd " "arch-update-tray.service" ", exécutez " "systemctl --user edit --full arch-update-tray.service " "et modifiez la ligne " "ExecStart=" ", comme ceci :"
.br
ExecStart=sh -c "sleep 3 && arch-update --tray"

.RB "\- Si vous utilisez un gestionnaire de fenêtres ou un compositeur Wayland, ajoutez une déclaration " "sleep " "avant la commande " "arch-update --tray " "à vos applications auto-start dans votre fichier de configuration, comme ceci :"
.br
"sleep 3 && arch-update --tray"

.RB "Si l'applet systray ne démarre toujours au démarrage du système, essayez de graduellement augmenter la valeur du " "sleep".

.TP
.B Modifier le cycle de vérification automatique
.RB "Si vous avez activé le " "systemd.timer" ", l'option " "--check " "est automatiquement lancée au démarrage du système puis une fois par heure."
.br
.RB "Si vous souhaitez modifier le cycle de vérification, exécutez la commande " "systemctl --user edit --full arch-update.timer " "et modifiez la valeur " "OnUnitActiveSec " "à votre convenance."
.br
.RB "Par exemple, si vous voulez qu'" "Arch-Update " "vérifie plutôt les mises à jour toutes les 10 minutes :"
.br

[...]
.br
[Timer]
.br
OnStartupSec=15
.br
.RB "OnUnitActiveSec=" "10m"
.br
[...]

.br
.RB "Les unités de temps sont " "s " "pour secondes, " "m " "pour minutes, " "h " "pour heures, " "d " "pour jours..."
.br
Voir https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html#Parsing%20Time%20Spans pour plus de détails.
.br

.RB "Dans le cas où vous voulez qu'" "Arch-Update " "ne vérifie les nouvelles mises à jour qu'une fois au démarrage du système, vous pouvez simplement supprimer la ligne " "OnUnitActiveSec " "complètement."

.TP
.B Forcer le fichier desktop à se lancer avec un émulateur de terminal spécifique
.BR "gio " "(qui est utilisé pour lancer le fichier " "arch-update.desktop " "quand l'applet systray est cliquée) ne supporte actuellement qu'une liste limitée d'émulateurs de terminal (voir https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L2701)."
.br
.RB "Si vous n'avez aucun de ces émulateurs de terminal installé sur votre système, il se peut que vous soyez confronté à un problème où cliquer sur l'applet systray ne fait rien et rapporte l'erreur suivante : " "[...] Unable to find terminal required for application".

.br
.RB "En attendant que Gnome implémente une méthode permettant aux utilisateurs d'utiliser l'émulateur de terminal de leur choix avec " "gio" ",vous pouvez contourner le problème en copiant le fichier " "arch-update.desktop " "dans " "$HOME/.local/share/applications/arch-update.desktop " "(par exemple, voir le chapitre " "'L'applet systray' "  "pour plus de détails) et en modifiant la ligne " "Exec " "pour 'forcer' " "arch-update " "à s'exécuter dans l'émulateur de terminal de votre choix."
.br
.RB "Par exemple, avec " "alacritty " "(vérifier le manuel de votre émulateur de terminal pour trouver la bonne option à utiliser) :"

.br
[...]
.br
.RB "Exec=" "alacritty -e " "arch-update"

.br
.RB "Alternativement, vous pouvez créer un lien symbolique de votre émulateur de terminal pointant vers " "/usr/bin/xterm" ", qui est l'option de 'secours' pour " "gio " "(par exemple, avec " "alacritty" ": " "sudo ln -s /usr/bin/alacritty /usr/bin/xterm" ") ou vous pouvez simplement installer un des émulateurs de terminal supportés par " "gio " "(voir https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L2701)."

.SH EXIT STATUS
.TP
.B 0
OK

.TP
.B 1
Option invalide

.TP
.B 2
Aucune commande d'élévation de privilège (sudo, doas ou run0) n'est installée ou celle définie dans le fichier de configuration arch-update.conf n'est pas disponible

.TP
.B 3
Erreur lors du lancement de l'applet systray d'Arch-update

.TP
.B 4
L'utilisateur n'a pas donné la confirmation de procéder

.TP
.B 5
Erreur lors de la mise à jour des paquets

.TP
.B 6
Erreur lors de l'appel de la commande reboot pour appliquer une mise à jour du noyau en attente

.TP
.B 7
.RB "Aucune mise à jour en attente durant l'utilisation de l'option " "-l/--list"

.TP
.B 8
.RB "Erreur lors de la génération d'un fichier de configuration avec l'option " "--gen-config"

.TP
.B 9
.RB "Erreur lors de la lecture du fichier de configuration avec l'option " "--show-config"

.TP
.B 10
.RB "Erreur lors de la création du fichier desktop autostart pour l'applet systray avec l'option " "--tray --enable"

.TP
.B 11
Erreur lors du redémarrage des services nécessitant un redémarrage après mise à jour

.TP
.B 12
Erreur lors du traitement des fichiers pacnew

.TP
.B 13
.RB "Erreur lors de l'édition du fichier de configuration avec l'option " "--edit-config"

.TP
.B 14
Le dossier de librairies n'a pas été trouvé

.TP
.B 15
L'éditeur "diff prog" défini dans le fichier de configuration arch-update.conf n'est pas disponible

.SH VOIR AUSSI
.BR checkupdates (8),
.BR pacman (8),
.BR pacdiff (8),
.BR paccache (8),
.BR yay (8),
.BR paru (8),
.BR pikaur (1),
.BR flatpak (1),
.BR arch-update.conf (5)

.SH BUGS
Signalez les bugs sur la page GitHub : https://github.com/Antiz96/arch-update/issues

.SH AUTHOR
Robin Candau <robincandau@protonmail.com>
