.TH "ARCH-UPDATE" "1" "November 2024" "Arch-Update 3.4.1" "Arch-Update Manual"

.SH NAME
arch-update \- An update notifier & applier for Arch Linux that assists you with important pre / post update tasks.

.SH SYNOPSIS
.B arch-update
[\fI\,OPTION\/\fR]

.SH DESCRIPTION
An update notifier & applier for Arch Linux that assists you with important pre / post update tasks and that includes a clickeable systray applet for an easy integration with any panel on any Desktop Environment / Window Manager.
.br
.RB "Optional support for AUR packages update (through " "paru" ", " "yay " "or " "pikaur" "), Flatpak packages update (through " "flatpak" ") and desktop notifications (through " "libnotify" ")."
.br
Arch-Update is designed to follow usual system maintenance steps, as described in the Arch Wiki at https://wiki.archlinux.org/title/System_maintenance.

.SH OPTIONS
.PP
If no option is passed, launch the relevant series of functions to perform a complete and proper update starting by displaying the list of packages available for update, then ask for the user's confirmation to proceed with the installation.
.br
.RB "It also supports AUR packages update (if " "paru" ", " "yay " "or " "pikaur " "is installed) and Flatpak packages update (if " "flatpak " "is installed)."
.br
Before performing the update, it offers to display the latest Arch Linux news to the user. By default, Arch news are only displayed if at least a new one has been published since the last run. Arch news published since the last run or at the same date are tagged as '[NEW]'.
.br
Arch-Update also checks for orphan packages, unused Flatpak packages, old and / or uninstalled cached packages in pacman's cache, pacnew & pacsave files, pending kernel update requiring a reboot to be applied as well as services requiring a post upgrade restart and, if there are, offers to process them.
.br
Those functions are launched when you click on the systray applet.

.PP

.TP
.B \-c, \-\-check
Check for available updates.
.br
It changes the systray icon and sends a desktop notification containing the number of available updates (if there are new available updates compared to the last check).
.br
.RB "It supports AUR packages update (if " "paru" ", " "yay " "or " "pikaur " "is installed) and Flatpak packages update (if " "flatpak " "is installed)."
.br
.RB "The " "\-\-check " "option is automatically launched at boot and then every hour if you enabled the associated " "systemd.timer " "with the following command:"
.br
.B systemctl \-\-user enable \-\-now arch-update.timer

.TP
.B \-l, \-\-list
Display the list of pending updates.

.TP
.B \-d, \-\-devel
Include AUR development packages updates.

.TP
.B \-n, \-\-news
Display latest Arch news.
.br
.RB "You can optionally specify how much Arch news to display as an argument, like so: " "arch-update --news 10" ". Defaults to 5."

.TP
.B \-D, \-\-debug
Display debug traces.

.TP
.B \-\-gen\-config
.RB "Generate a default / example " "arch-update.conf " "configuration file (see the " "arch-update.conf(5) " "man page for more details)."
.br
.RB "You can optionally pass the " "--force " "argument to overwrite any existing " "arch-update.conf " "configuration file."

.TP
.B \-\-show\-config
.RB "Display the " "arch-update.conf " "configuration file currently used (if it exists)."

.TP
.B \-\-edit\-config
.RB "Edit the " "arch-update.conf " "configuration file currently used (if it exists)."

.TP
.B \-\-tray
Start the Arch-Update systray applet.
.br
.RB "To start it automatically at boot, you can either run the " "arch-update --tray --enable " "command (preferred method for most Desktop Environments, uses XDG Autostart) or enable the associated systemd service (in case your Desktop Environment doesn't support XDG Autostart) by running " "systemctl \-\-user enable \-\-now arch-update-tray.service".
.br
.RB "If you use a window manager or a Wayland compositor, you can add the " "arch-update --tray " "command to your auto-start apps in your configuration file instead."

.TP
.B \-v, \-\-version
Display version information.

.TP
.B \-h, \-\-help
Display the help message.

.TP
.RB "Certain options can be enabled, disabled or modified via the " "arch-update.conf " "configuration file, see the " "arch-update.conf(5) " "man page."

.SH USAGE
.TP
.B The systray applet
.RB "To start the systray applet, launch the " "Arch-Update Systray Applet " "application from your app menu."

To start it automatically at boot, you can either:

.RB "- Run the following command (preferred method for most Desktop Environments, uses XDG Autostart): " "arch-update \-\-tray \-\-enable"
.br
.RB "- Enable the associated systemd service (in case your Desktop Environment doesn't support XDG Autostart): " "systemctl \-\-user enable \-\-now arch-update-tray.service"

.RB "If you use a Window Manager or a Wayland Compositor, you can add the " "arch-update \-\-tray " "command to your auto-start apps in your configuration file instead."

.BR "If the systray applet doesn't start at boot regardless" ", please read the " "'The systray applet does not start at boot' " "chapter in the " "Tips and Tricks " "section below."

.RB "The systray icon will automatically change depending on the current state of your system ('up to date' or 'updates available'). When clicked, it launches " "arch-update " "via the " "arch-update.desktop " file.

.RB "The systray applet attempts to read the " "arch-update.desktop " "file at the below paths and in the following order:"

\- $XDG_DATA_HOME/applications/arch-update.desktop
.br
\- $HOME/.local/share/applications/arch-update.desktop
.br
\- $XDG_DATA_DIRS/applications/arch-update.desktop
.br
\- /usr/local/share/applications/arch-update.desktop <-- Default installation path when installing Arch-Update from source
.br
\- /usr/share/applications/arch-update.desktop <-- Default installation path when installing Arch-Update from the AUR

.RB "In case you want (or need) to customize the " "arch-update.desktop " "file, copy it in a path that has a higher priority than the default installation path and modify it there (to ensure that your custom " "arch-update.desktop " "file supersedes the default one and that your modifications are not being overwritten on updates)."

.br
.RB "This can be useful to force the " "arch-update.desktop " "file to launch " "Arch-Update " "within a specific terminal emulator for instance."
.br
.BR "If clicking the systray applet does nothing" ", please read the " "'Force the desktop file to run with a specific terminal emulator' " "chapter in the " "Tips and Tricks " "section below."

.TP
.B The systemd timer
.RB "There is a systemd service in " "/usr/lib/systemd/user/arch-update.service " "(or in " "/etc/systemd/user/arch-update.service " "if you installed arch-update from source) that executes the " "\-\-check " "function when launched. To start it automatically " "at boot and then once every hour " "enable the associated systemd timer (the auto-check cycle can be modified to your liking. See the TIPS AND TRICKS chapter below):"
.br
.B systemctl \-\-user enable \-\-now arch-update.timer

.SH TIPS AND TRICKS 
.TP
.B AUR Support
.RB "Arch-Update supports AUR packages update when checking and installing updates if " "paru" ", " "yay " "or " "pikaur " "is installed."
.br
See https://github.com/morganamilo/paru and https://aur.archlinux.org/packages/paru
.br
See https://github.com/Jguer/yay and https://aur.archlinux.org/packages/yay
.br
See https://github.com/actionless/pikaur and https://aur.archlinux.org/packages/pikaur

.TP
.B Flatpak Support
.RB "Arch-Update supports Flatpak packages update when checking and installing updates (as well as removing unused Flatpak packages) if " "flatpak " "is installed."
.br
See https://www.flatpak.org/ and https://archlinux.org/packages/extra/x86_64/flatpak/

.TP
.B Desktop notifications Support
.RB "Arch-Update supports desktop notifications when performing the " "--check " "function if " "libnotify (notify-send) " "is installed."
.br
See https://wiki.archlinux.org/title/Desktop_notifications

.TP
.B The systray applet does not start at boot
.RB "Make sure you followed instructions of the " "'The systray applet' " "chapter in the " "Usage " "section above."

.RB "If the systray applet doesn't start regardless, this could be the result of a " "race condition".
.RB "In such case, it might be useful to slightly delay the startup of the systray applet by using a " "sleep " "statement beforehand:"

.RB "\- If you used " "arch-update --tray --enable" ", modify the " "Exec= " "line in the " "arch-update-tray.desktop " "file (which is under " "~/.config/autostart/ " "by default), like so:"
.br
Exec=sh -c "sleep 3 && arch-update --tray"

.RB "\- If you used the " "arch-update-tray.service " "systemd service, run " "systemctl --user edit --full arch-update-tray.service " "and modify the " "ExecStart= " "line, like so:"
.br
ExecStart=sh -c "sleep 3 && arch-update --tray"

.RB "\- If you're using a standalone Window Manager or a Wayland Compositor, add a " "sleep " "statement before the " "arch-update --tray " "command in your auto-start apps in your configuration file, like so:"
.br
sleep 3 && arch-update --tray

.RB "If the systray applet still does not start at boot, try to gradually increase the value of the " "sleep".

.TP
.B Modify the auto-check cycle
.RB "If you enabled the " "systemd.timer" ", the " "--check " "option is automatically launched at boot and then once per hour."
.br
.RB "If you want to change the check cycle, run " "systemctl --user edit --full arch-update.timer " "and modify the " "OnUnitActiveSec " "value to your liking."
.br
.RB "For instance, if you want " "Arch-Update " "to check for new updates every 10 minutes instead:"
.br

[...]
.br
[Timer]
.br
OnStartupSec=15
.br
.RB "OnUnitActiveSec=" "10m"
.br
[...]

.br
.RB "Time units are " "s " "for seconds, " "m " "for minutes, " "h " "for hours, " "d " "for days..."
.br
See https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html#Parsing%20Time%20Spans for more details.
.br

.RB "In case you want " "Arch-Update " "to check for new updates only once at boot, you can simple delete the " "OnUnitActiveSec " "line completely."

.TP
.B Force the desktop file to run with a specific terminal emulator
.BR "gio " "(which is used to launch the " "arch-update.desktop " "file when the systray applet is clicked) currently supports a limited list of terminal emulators (see https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L2701).
.br
.RB "If you don't have any of these terminal emulators installed on your system, you might face an issue where clicking the systray applet does nothing and reports the following error: " "[...] Unable to find terminal required for application".

.br
.RB "While waiting for Gnome to implement a way to allow people using their terminal emulator of choice with " "gio" ", you can workaround this issue by copying the " "arch-update.desktop " "file to " "$HOME/.local/share/applications/arch-update.desktop " "(for instance, see " "'The systray applet' " "chapter for more details) and modifying the " "Exec " "line in it to 'force' " "arch-update " "to run with your terminal emulator of choice."
.br
.RB "For instance, with " "alacritty " "(check your terminal emulator's manual to find the correct option to use):"

.br
[...]
.br
.RB "Exec=" "alacritty -e " "arch-update"

.br
.RB "Alternatively, you can create a symlink for your terminal emulator that points to " "/usr/bin/xterm" ", which is the fallback option for " "gio " "(for instance, with " "alacritty" ": " "sudo ln -s /usr/bin/alacritty /usr/bin/xterm" ") or you can simply install one of the terminal emulators supported by " "gio " "(see https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L2701)."

.SH EXIT STATUS
.TP
.B 0
OK

.TP
.B 1
Invalid option

.TP
.B 2
No privilege elevation command (sudo, doas or run0) is installed or the one set in the arch-update.conf configuration file isn't found

.TP
.B 3
Error when launching the Arch-Update systray applet

.TP
.B 4
User didn't gave the confirmation to proceed

.TP
.B 5
Error when updating the packages

.TP
.B 6
Error when calling the reboot command to apply a pending kernel update

.TP
.B 7
.RB "No pending update when using the " "-l / --list " "option"

.TP
.B 8
.RB "Error when generating a configuration file with the " "--gen-config " "option"

.TP
.B 9
.RB "Error when reading the configuration file with the " "--show-config " "option"

.TP
.B 10
.RB "Error when creating the autostart desktop file for the systray applet with the " "--tray --enable " "option"

.TP
.B 11
Error when restarting services that require a post upgrade restart

.TP
.B 12
 Error during the pacnew files processing

.TP
.B 13
.RB "Error when editing the configuration file with the " "--edit-config " "option"

.TP
.B 14
Libraries directory not found

.TP
.B 15
The diff prog editor set in the arch-update.conf configuration file isn't found

.SH SEE ALSO
.BR checkupdates (8),
.BR pacman (8),
.BR pacdiff (8),
.BR paccache (8),
.BR paru (8),
.BR yay (8),
.BR pikaur (1),
.BR flatpak (1),
.BR arch-update.conf (5)

.SH BUGS
Please report bugs to the GitHub page: https://github.com/Antiz96/arch-update/issues

.SH AUTHOR
Robin Candau <robincandau@protonmail.com>
