.TH "ARCH-UPDATE.CONF" "5" "March 2024" "Arch-Update 1.14.3" "Arch-Update Manual"

.SH NAME
arch-update.conf \- arch-update configuration file.

.SH SYNOPSIS
$XDG_CONFIG_HOME/arch-update/arch-update.conf, $HOME/.config/arch-update/arch-update.conf

.SH DESCRIPTION
.RI "Arch-Update's " "optional " "configuration file."

.RB "Arch-Update first attempts to read the file at " "$XDG_CONFIG_HOME/arch-update/arch-update.conf " "then at " "$HOME/.config/arch-update/arch-update.conf " "if " "$XDG_CONFIG_HOME " "is not set, or the file doesn't exist."

.SH OPTIONS
.PP
Options are case sensitive, so capital letters have to be respected.

.PP

.TP
.B NoColor
Do not colorize output.

.TP
.B NoVersion
.RB "Do not show versions changes for packages when listing pending updates (including when using the " "-l/--list " "option, see the " "arch-update(1) " "man page for more details)."

.TP
.B AlwaysShowNews
Always display Arch news before updating, regardless of whether there's a new one since the last run or not.

.TP
.B NewsNum=[Num]
.RB "Number of Arch news to display before updating and with the " "-n/--news " "option (see the " "arch-update(1) " "man page for more details). Defaults to 5."

.TP
.B KeepOldPackages=[Num]
Number of old packages' versions to keep in pacman's cache. Defaults to 3.

.TP
.B KeepUninstalledPackages=[Num]
Number of uninstalled packages' versions to keep in pacman's cache. Defaults to 0.

.SH SEE ALSO
.BR arch-update (1)

.SH BUGS
Please report bugs to the GitHub page: https://github.com/Antiz96/arch-update/issues

.SH AUTHOR
Robin Candau <robincandau@protonmail.com>
