name: CI
on: pull_request

jobs:
  Test:
    runs-on:
      - self-hosted
      - CI-CD

    steps:
      - name: Clone repo
        uses: actions/checkout@v7

      - name: Run actionlint
        run: actionlint -ignore 'label "CI-CD" is unknown' .github/workflows/CI.yml

      - name: Run codespell
        run: codespell --skip="README-fr.md,./doc/man/fr,./po" --enable-colors

      - name: Run mdl
        run: mdl --style .github/workflows/mdl_style.rb .

      - name: Run shellcheck
        run: find . -name '*.sh' -exec shellcheck --color=always {} +

      - name: Run cargo fmt
        run: cargo fmt --check --manifest-path src/tray/Cargo.toml

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features --manifest-path src/tray/Cargo.toml -- -D warnings

      - name: Run make
        run: make

      - name: Run make test
        run: make test

      - name: Run make clean
        run: make clean

      - name: Cargo cleanup
        run: rm -rvf ~/.cargo
